; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.5.0-rc.2+4 on Sun Jan 21 2024 17:34:03 GMT+0100 (Central European Standard Time)

M116 P0 ; wait for tool temperatures to be reached
